version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  backend:
    build: ./backend
    command: gunicorn SZUAPsite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
      - static_volume:/usr/src/backend/staticfiles
      - media_volume:/usr/src/backend/mediafiles
    expose:
      - 8000
    env_file:
      - ./backend/.env
    depends_on:
      - db

  nginx:
    build:
      context: . # because you're COPYing files from other components
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/src/backend/staticfiles
      - media_volume:/usr/src/backend/mediafiles
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume: