# Generated by Django 3.1.8 on 2022-04-06 14:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('description', tinymce.models.HTMLField(max_length=700, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Блок: О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Buisness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('description', tinymce.models.HTMLField(max_length=700, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Блок: О деятельности',
                'verbose_name_plural': 'О деятельности',
            },
        ),
        migrations.CreateModel(
            name='Carier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('description', tinymce.models.HTMLField(max_length=700, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Блок: Карьера”',
                'verbose_name_plural': 'Карьера',
            },
        ),
        migrations.CreateModel(
            name='HelloPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField(max_length=300, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='hello_section', verbose_name='Изображение')),
                ('imageAligin', models.FloatField(choices=[(0, 'Слева'), (1, 'Справа')], default=0, verbose_name='Расположение картинки')),
            ],
            options={
                'verbose_name': 'Блок: ООО “СЗУАП-АУДИТ”',
                'verbose_name_plural': 'Блоки: ООО “СЗУАП-АУДИТ”',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Дата обнавления')),
                ('content', tinymce.models.HTMLField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='services_section', verbose_name='Изображение')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.IntegerField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Статус Поста')),
                ('post_type', models.IntegerField(choices=[(0, 'Аудиторский отчет'), (1, 'Новость')], default=1, verbose_name='Тип поста')),
            ],
            options={
                'verbose_name': 'Блок: Пост (Новость, Аудиторский отчет)',
                'verbose_name_plural': 'Блоки: Постов (Новости, Аудиторские отчеты)',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='services_section', verbose_name='Изображение')),
                ('description', tinymce.models.HTMLField(max_length=1500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Блок: Услуги',
                'verbose_name_plural': 'Блоки: Услуги',
            },
        ),
    ]
