# Generated by Django 3.2.7 on 2021-11-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelloPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=170, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='hello_section', verbose_name='Изображение')),
                ('aliginLeft', models.FloatField(default=True, verbose_name='Картинка слева')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=170, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='services_section', verbose_name='Изображение')),
                ('description', models.CharField(max_length=600, verbose_name='Описание')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.IntegerField(choices=[(0, 'Аудиторский отчет'), (1, 'Новость')], default=1, verbose_name='Тип поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Статус Поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обнавления'),
        ),
    ]
