# Generated by Django 3.1.8 on 2022-04-11 09:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buisness',
            name='label',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=tinymce.models.HTMLField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='buisness',
            name='description',
            field=tinymce.models.HTMLField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='carier',
            name='description',
            field=tinymce.models.HTMLField(max_length=1000, verbose_name='Описание'),
        ),
    ]
