# Generated by Django 3.2.7 on 2021-11-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211125_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hellopage',
            options={'verbose_name': 'Блок: ООО “СЗУАП-АУДИТ”'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on'], 'verbose_name': 'Блок: Постов (Новости, Аудиторские отчеты)'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Блок: Услуги'},
        ),
        migrations.RemoveField(
            model_name='hellopage',
            name='aliginLeft',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='hellopage',
            name='imageAligin',
            field=models.FloatField(choices=[(0, 'Слева'), (1, 'Справа')], default=0, verbose_name='Расположение картинки'),
        ),
    ]
