# Generated by Django 3.2.7 on 2021-11-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20211125_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hellopage',
            options={'verbose_name': 'Блок: ООО “СЗУАП-АУДИТ”', 'verbose_name_plural': 'Блоки: ООО “СЗУАП-АУДИТ”'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on'], 'verbose_name': 'Блок: Пост (Новость, Аудиторский отчет)', 'verbose_name_plural': 'Блоки: Постов (Новости, Аудиторские отчеты)'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Блок: Услуги', 'verbose_name_plural': 'Блоки: Услуги'},
        ),
    ]
