# Generated by Django 3.1.8 on 2022-04-19 07:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220413_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField(max_length=1000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Блок: Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.IntegerField(choices=[(1, 'Аудиторский отчет'), (0, 'Новость')], default=1, verbose_name='Тип поста'),
        ),
    ]
