# Generated by Django 3.1.8 on 2022-04-19 08:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20220419_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=tinymce.models.HTMLField(max_length=1500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='buisness',
            name='description',
            field=tinymce.models.HTMLField(max_length=1500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='carier',
            name='description',
            field=tinymce.models.HTMLField(max_length=1500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='description',
            field=tinymce.models.HTMLField(max_length=1500, verbose_name='Описание'),
        ),
    ]
