# Generated by Django 3.1.8 on 2021-11-25 11:33

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20211125_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hellopage',
            name='description',
            field=tinymce.models.HTMLField(max_length=170, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='hellopage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=tinymce.models.HTMLField(max_length=600, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
