# Generated by Django 3.1.8 on 2021-11-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20211125_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='services_section', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
