# Generated by Django 3.1.8 on 2022-08-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, default=None, upload_to='services_section', verbose_name='Документы'),
        ),
    ]
